"""
End-to-end RAG Pipeline

Flow:
User Query
    -> Query Embedding
    -> ChromaDB Retrieval
    -> Context Assembly
    -> Gemini Generation
    -> Answer + Sources
"""

import json
import os
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from google.genai import types

from retrieval import embed_query, retrieve, get_collection

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_FILE = BASE_DIR / "outputs" / "rag_pipeline_output.txt"


def get_chat_model():
    """Read the configured chat model lazily from the environment."""
    model = os.getenv("CHAT_MODEL", "gemini-2.0-flash")
    if not model:
        raise ValueError("CHAT_MODEL not found in environment.")
    return model


def get_gemini_client():
    """Create the Gemini client only when needed and only if the API key is configured."""
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY not found in environment.")
    return genai.Client(api_key=api_key)


# ---------------------------------------------------------
# 1. EMBED QUERY
# ---------------------------------------------------------

def embed_query_stage(query):
    """Convert the user query into an embedding vector."""
    return embed_query(query)


# ---------------------------------------------------------
# 2. RETRIEVE CONTEXT
# ---------------------------------------------------------

def retrieve_context(query_vector, k=3):
    """
    Retrieve the most relevant chunks from ChromaDB.

    The query vector is already generated by the embedding stage.
    """
    collection = get_collection()

    results = collection.query(
        query_embeddings=[query_vector],
        n_results=k,
        include=["documents", "metadatas", "distances"],
    )

    documents = results.get("documents", [[]])[0]
    metadatas = results.get("metadatas", [[]])[0]
    distances = results.get("distances", [[]])[0]

    chunks = []

    for text, metadata, distance in zip(
        documents,
        metadatas,
        distances,
    ):
        chunks.append(
            {
                "text": text,
                "metadata": metadata,
                "score": round(1 - distance, 4),
            }
        )

    return chunks


# ---------------------------------------------------------
# 3. ASSEMBLE CONTEXT
# ---------------------------------------------------------

def assemble_context(chunks):
    """
    Combine retrieved chunks into grounded context
    with source information.
    """

    if not chunks:
        return ""

    parts = []

    for index, chunk in enumerate(chunks, start=1):
        metadata = chunk.get("metadata", {})

        source = metadata.get("source", "unknown")
        chunk_index = metadata.get("chunk_index", "unknown")
        section = metadata.get("section")

        source_info = (
            f"[{index}] Source: {source} | "
            f"Chunk: {chunk_index}"
        )

        if section:
            source_info += f" | Section: {section}"

        parts.append(
            f"{source_info}\n{chunk['text']}"
        )

    return "\n\n".join(parts)


# ---------------------------------------------------------
# 4. GENERATE ANSWER
# ---------------------------------------------------------

def generate_answer(query, context):
    """
    Generate a grounded answer using only the retrieved context.
    """

    if not context:
        return "I could not find relevant context for this question."

    client = get_gemini_client()
    model_name = get_chat_model()

    prompt = f"""
Answer the user's question using ONLY the context provided below.

If the context does not contain enough information to answer,
say that the available documents do not contain enough information.

Do not invent facts.

Context:
{context}

Question:
{query}
"""

    response = client.models.generate_content(
        model=model_name,
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0.2,
        ),
    )

    return response.text.strip()


# ---------------------------------------------------------
# 5. COMPLETE RAG PIPELINE
# ---------------------------------------------------------

def answer_query(query, k=3):
    """
    Run the complete RAG pipeline.
    """

    if query is None or not str(query).strip():
        raise ValueError("Question is required.")

    query = str(query).strip()

    # Stage 1: Embed
    query_vector = embed_query_stage(query)

    # Stage 2: Retrieve
    chunks = retrieve_context(
        query_vector,
        k=k,
    )

    # Handle empty retrieval
    if not chunks:
        return {
            "answer": "I could not find relevant context for this question.",
            "sources": [],
            "chunks": [],
        }

    # Stage 3: Assemble context
    context = assemble_context(chunks)

    # Stage 4: Generate grounded answer
    answer = generate_answer(
        query,
        context,
    )

    sources = []

    for chunk in chunks:
        metadata = chunk.get("metadata", {})

        sources.append(
            {
                "source": metadata.get("source"),
                "chunk_index": metadata.get("chunk_index"),
                "section": metadata.get("section"),
                "score": chunk.get("score"),
            }
        )

    return {
        "answer": answer,
        "sources": sources,
        "chunks": chunks,
        "context": context,
    }


# ---------------------------------------------------------
# SAMPLE END-TO-END RUN
# ---------------------------------------------------------

def main():

    query = "What does property insurance protect?"

    print("=" * 70)
    print("RAG PIPELINE")
    print("=" * 70)

    print(f"\nQuery:\n{query}")

    print("\n[1] Embedding query...")
    query_vector = embed_query_stage(query)

    print(f"Query vector length: {len(query_vector)}")

    print("\n[2] Retrieving relevant chunks...")

    chunks = retrieve_context(
        query_vector,
        k=3,
    )

    print(f"Chunks retrieved: {len(chunks)}")

    if not chunks:
        print("\nNo relevant context found.")
        print("Pipeline stopped before generation.")

        report = [
            "RAG PIPELINE OUTPUT",
            "=" * 70,
            f"Query : {query}",
            "",
            "No relevant chunks were retrieved.",
            "Answer : I could not find relevant context for this question.",
            "Sources : None",
        ]

    else:

        print("\nTop-ranked sources:")

        for rank, chunk in enumerate(
            chunks,
            start=1,
        ):
            metadata = chunk.get("metadata", {})

            print(
                f"{rank}. "
                f"{metadata.get('source')} "
                f"(score={chunk.get('score')})"
            )

        print("\n[3] Assembling context...")

        context = assemble_context(chunks)

        print("Context assembled successfully.")

        print("\n[4] Generating grounded answer...")

        answer = generate_answer(
            query,
            context,
        )

        print("\nGenerated Answer:")
        print(answer)

        print("\nSources:")

        for chunk in chunks:
            metadata = chunk.get("metadata", {})

            print(
                f"- {metadata.get('source')} "
                f"(chunk={metadata.get('chunk_index')}, "
                f"score={chunk.get('score')})"
            )

        report = [
            "RAG PIPELINE OUTPUT",
            "=" * 70,
            f"Embedding model : {os.getenv('EMBEDDING_MODEL')}",
            f"Chat model      : {CHAT_MODEL}",
            f"Query           : {query}",
            "",
            "RETRIEVED SOURCES",
            "-" * 70,
        ]

        for rank, chunk in enumerate(
            chunks,
            start=1,
        ):
            metadata = chunk.get("metadata", {})

            report.append(
                f"{rank}. "
                f"{metadata.get('source')} | "
                f"chunk={metadata.get('chunk_index')} | "
                f"score={chunk.get('score')}"
            )

        report.extend(
            [
                "",
                "ASSEMBLED CONTEXT",
                "-" * 70,
                context,
                "",
                "GENERATED ANSWER",
                "-" * 70,
                answer,
                "",
                "PIPELINE FLOW",
                "-" * 70,
                "User Query",
                "    -> Query Embedding",
                "    -> ChromaDB Retrieval",
                "    -> Context Assembly",
                "    -> Gemini Generation",
                "    -> Answer + Sources",
            ]
        )

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    OUTPUT_FILE.write_text(
        "\n".join(report),
        encoding="utf-8",
    )

    print(
        f"\nOutput saved to {OUTPUT_FILE}"
    )


if __name__ == "__main__":
    main()